### ISSUE TITLE
Image Downloading 

### ISSUE THREAD

**Issue by Glloret** [Glloret/TweetWall#1]
Ahora se descargan las imágenes adjuntas del Tweet dos veces, una por el navegador y otra por node.js para guardarla en directorio de imágenes.

**Comment by libercv** [comment]
Ya carga las imágenes adjuntas una vez y las muestra de la carpeta de descargadas. Ahora falta hacer lo mismo con las imágenes de avatares

**Comment by libercv** [comment]
Guardadas también las imágenes de los avatares.
